function PS5cost (ps5Cost: number) {
    totalCost = ps5Cost
    return totalCost
}
function PS5f () {
    if (checkMoney()) {
        PS5 = sprites.create(img`
            ........................
            ........................
            ........................
            ......1ffff1............
            .......1ff1.............
            .......1ff1.............
            .......1ff1.............
            .......1ff1.............
            .......1ff1.............
            .......1ff1.............
            .......1ff1.............
            .......1ff1.............
            .......1ff1.............
            ........................
            ........................
            ........................
            `, SpriteKind.Player)
        PS5.sayText("You can get a PS5!")
        scene.setBackgroundColor(8)
    } else {
        noPS5 = sprites.create(img`
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . 2 . . . . . . . 2 . . . . 
            . . . . 2 . . . . . 2 . . . . . 
            . . . . . 2 . . . 2 . . . . . . 
            . . . . . . 2 . 2 . . . . . . . 
            . . . . . . . 2 . . . . . . . . 
            . . . . . . 2 . 2 . . . . . . . 
            . . . . . 2 . . . 2 . . . . . . 
            . . . . 2 . . . . . 2 . . . . . 
            . . . 2 . . . . . . . 2 . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            `, SpriteKind.Player)
        noPS5.sayText("You can't get a PS5.", 1000, false)
        pause(2000)
        while (Money < PS5cost(500)) {
            newMoney = game.askForString("Do you have more money?", 3)
            if (newMoney == "yes") {
                Money = game.askForNumber("How much money do you have?", 4)
            }
        }
        if (Money >= 500) {
            mewPS5 = sprites.create(img`
                ........................
                ........................
                ........................
                ......1ffff1............
                .......1ff1.............
                .......1ff1.............
                .......1ff1.............
                .......1ff1.............
                .......1ff1.............
                .......1ff1.............
                .......1ff1.............
                .......1ff1.............
                .......1ff1.............
                ........................
                ........................
                ........................
                `, SpriteKind.Player)
            mewPS5.sayText("You can get a PS5!")
            scene.setBackgroundColor(8)
        }
    }
}
function checkMoney () {
    if (Money >= PS5cost(500)) {
        return true
    } else {
        return false
    }
}
let mewPS5: Sprite = null
let newMoney = ""
let noPS5: Sprite = null
let PS5: Sprite = null
let totalCost = 0
let Money = 0
Money = game.askForNumber("How much money do you have?", 4)
PS5f()
